### ISSUE TITLE
position not updating when hitting stoneCollider??

### ISSUE THREAD

**Issue by mohitarty** [t1az2z/RockyClimb_mockup-TestTask#1]
Why position is not updating when hitting stoneCollider??
player do not move upward when click on stone on time

**Comment by t1az2z** [comment]
On entering trigger updates stoneOffset variable, that passed to the CharacterControll script. Player position updates in CharacterControll.

**Comment by mohitarty** [comment]
after running in unity i am unable  to move up hero position , it is not working for me please help sir

**Comment by t1az2z** [comment]
Do you run the latest version of the project? It looks like death condition also is missing. Haven't you changed the code?
Here is gif of the freshly downloaded project running in unity 2018.1.6f1
![rctt](https://user-images.githubusercontent.com/14869912/42033460-a0832bc0-7ae5-11e8-9f5c-4dc61e070c16.gif)

**Comment by mohitarty** [comment]
Can I play provide me the link of latest source code

**Comment by t1az2z** [comment]
It is the latest version in this repository.

**Comment by mohitarty** [comment]
Yes I am running this one too but I am having problems like I mentioned above if u can kindly provide drive link or mail me the source code it would be good for me 
Mail at = > mohitme100@gmail.com
